// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkIDC76UB3WaE05KFcQItvV8unyh6aBtc',
    appId: '1:545144646009:web:dded0d10701dbf674ea7a8',
    messagingSenderId: '545144646009',
    projectId: 'track-c309e',
    authDomain: 'track-c309e.firebaseapp.com',
    storageBucket: 'track-c309e.appspot.com',
    measurementId: 'G-9YKQ1QK6PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9GiiNEJqfLtib8a2DVopsqrByZKsVAU',
    appId: '1:545144646009:android:05ec72528f81d79d4ea7a8',
    messagingSenderId: '545144646009',
    projectId: 'track-c309e',
    storageBucket: 'track-c309e.appspot.com',
  );
}
